apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scores-api.fullname" . }}-config
  labels:
    {{- include "scores-api.labels" . | nindent 4 }}
data:
  welcomeMessage: {{ .Values.config.welcomeMessage | quote }}
